//
//  DataWritingScripts.swift
//  Hallow
//
//  Created by Alex Jones on 8/9/18.
//  Copyright © 2018 Hallow. All rights reserved.
//

import Foundation
import FirebaseFirestore
import FirebaseStorage
import Firebase

class DataWritingScripts {
    
    // MARK: Types
    
    static func uploadTypes() {
        let category = "Types"
        let files = ["Dailes",
                     "Praylists",
                     "Challenges"]
        let desc = ["Daily description",
                        "Praylist description",
                        "Challenges description"]
        var i = 0
        
        for file in files {
            let db = Firestore.firestore()
            db.collection(category).document(file).setData([
                "Name": file,
                "Index": i,
                "Description": desc[i]
                ]) { err in
                    if let err = err {
                        fatalError("Error adding document: \(err)")
                    } else {
                        print("Document added")
                    }
            }
            i += 1
        }
    }

    // MARK: Chapters
    
    static func uploadChapters() {
        let category = "Chapters"
        let files = ["Meditation",
                     "Examen",
                     "Lectio",
                     "Spiritual Writing",
                     "Joy",
                     "Humility",
                     "Making decisions",
                     "Gratitude",
                     "Calm",
                     "Letting go",
                     "Love",
                     "Intro",
                     "Our Father",
                     "Psalms",
                     "Stations"]
        let desc = ["TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD",
                     "TBD"]
        let categoryIndex = [0,
                             0,
                             0,
                             0,
                             1,
                             1,
                             1,
                             1,
                             1,
                             1,
                             1,
                             2,
                             2,
                             2,
                             2]
        var i = 0
        
        for file in files {
            let db = Firestore.firestore()
            db.collection(category).document(file).setData([
                "Name": file,
                "Index": i,
                "Description": desc[i],
                "Category Index": categoryIndex[i]
                ]) { err in
                    if let err = err {
                        fatalError("Error adding document: \(err)")
                    } else {
                        print("Document added")
                    }
            }
            i += 1
        }
    }
    
    // MARK: Sessions
    
    static func uploadPrayers() {
        let category = "Prayers"
        let files = ["Meditation - 5 mins - F - 1.mp3",
                     "Meditation - 10 mins - F - 1.mp3",
                     "Meditation - 15 mins - F - 1.mp3",
                     "Meditation - 5 mins - A - 1.mp3",
                     "Meditation - 10 mins - A - 1.mp3",
                     "Meditation - 15 mins - A - 1.mp3",
                     "Meditation - 5 mins - F - 2.mp3",
                     "Meditation - 10 mins - F - 2.mp3",
                     "Meditation - 15 mins - F - 2.mp3",
                     "Meditation - 5 mins - A - 2.mp3",
                     "Meditation - 10 mins - A - 2.mp3",
                     "Meditation - 15 mins - A - 2.mp3",
                     "Meditation - 5 mins - F - 3.mp3",
                     "Meditation - 10 mins - F - 3.mp3",
                     "Meditation - 15 mins - F - 3.mp3",
                     "Meditation - 5 mins - A - 3.mp3",
                     "Meditation - 10 mins - A - 3.mp3",
                     "Meditation - 15 mins - A - 3.mp3",
                     "Examen - 5 mins - F - 1.mp3",
                     "Examen - 10 mins - F - 1.mp3",
                     "Examen - 15 mins - F - 1.mp3",
                     "Examen - 5 mins - A - 1.mp3",
                     "Examen - 10 mins - A - 1.mp3",
                     "Examen - 15 mins - A - 1.mp3",
                     "Examen - 5 mins - F - 2.mp3",
                     "Examen - 10 mins - F - 2.mp3",
                     "Examen - 15 mins - F - 2.mp3",
                     "Examen - 5 mins - A - 2.mp3",
                     "Examen - 10 mins - A - 2.mp3",
                     "Examen - 15 mins - A - 2.mp3",
                     "Examen - 5 mins - F - 3.mp3",
                     "Examen - 10 mins - F - 3.mp3",
                     "Examen - 15 mins - F - 3.mp3",
                     "Examen - 5 mins - A - 3.mp3",
                     "Examen - 10 mins - A - 3.mp3",
                     "Examen - 15 mins - A - 3.mp3",
                     "Lectio - 5 mins - F - 1.mp3",
                     "Lectio - 10 mins - F - 1.mp3",
                     "Lectio - 15 mins - F - 1.mp3",
                     "Lectio - 5 mins - A - 1.mp3",
                     "Lectio - 10 mins - A - 1.mp3",
                     "Lectio - 15 mins - A - 1.mp3",
                     "Lectio - 5 mins - F - 2.mp3",
                     "Lectio - 10 mins - F - 2.mp3",
                     "Lectio - 15 mins - F - 2.mp3",
                     "Lectio - 5 mins - A - 2.mp3",
                     "Lectio - 10 mins - A - 2.mp3",
                     "Lectio - 15 mins - A - 2.mp3",
                     "Lectio - 5 mins - F - 3.mp3",
                     "Lectio - 10 mins - F - 3.mp3",
                     "Lectio - 15 mins - F - 3.mp3",
                     "Lectio - 5 mins - A - 3.mp3",
                     "Lectio - 10 mins - A - 3.mp3",
                     "Lectio - 15 mins - A - 3.mp3",
                     "francisSample",
                     "abbySample"]
        
        let title = ["Day 1",
                     "Day 1",
                     "Day 1",
                     "Day 1",
                     "Day 1",
                     "Day 1",
                     "Day 2",
                     "Day 2",
                     "Day 2",
                     "Day 2",
                     "Day 2",
                     "Day 2",
                     "Day 3",
                     "Day 3",
                     "Day 3",
                     "Day 3",
                     "Day 3",
                     "Day 3",
                     "Day 4",
                     "Day 4",
                     "Day 4",
                     "Day 4",
                     "Day 4",
                     "Day 4",
                     "Day 5",
                     "Day 5",
                     "Day 5",
                     "Day 5",
                     "Day 5",
                     "Day 5",
                     "Day 6",
                     "Day 6",
                     "Day 6",
                     "Day 6",
                     "Day 6",
                     "Day 6",
                     "Day 7",
                     "Day 7",
                     "Day 7",
                     "Day 7",
                     "Day 7",
                     "Day 7",
                     "Day 8",
                     "Day 8",
                     "Day 8",
                     "Day 8",
                     "Day 8",
                     "Day 8",
                     "Day 9",
                     "Day 9",
                     "Day 9",
                     "Day 9",
                     "Day 9",
                     "Day 9",
                     "Sample",
                     "Sample"]
        
        let desc = ["Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Finding peace in silence",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "Reflecting on your day",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "A conversation with God",
                    "Francis sample",
                    "Abby sample"]
        
        let desc2 = ["Hello and welcome!  These first 9 sessions will guide you through 3 different methods of prayer. The first 3 sessions will focus on finding peace in silence with God while using our breath to collect ourselves.",
                     "Hello and welcome!  These first 9 sessions will guide you through 3 different methods of prayer. The first 3 sessions will focus on finding peace in silence with God while using our breath to collect ourselves.",
                     "Hello and welcome!  These first 9 sessions will guide you through 3 different methods of prayer. The first 3 sessions will focus on finding peace in silence with God while using our breath to collect ourselves.",
                     "Hello and welcome!  These first 9 sessions will guide you through 3 different methods of prayer. The first 3 sessions will focus on finding peace in silence with God while using our breath to collect ourselves.",
                     "Hello and welcome!  These first 9 sessions will guide you through 3 different methods of prayer. The first 3 sessions will focus on finding peace in silence with God while using our breath to collect ourselves.",
                     "Hello and welcome!  These first 9 sessions will guide you through 3 different methods of prayer. The first 3 sessions will focus on finding peace in silence with God while using our breath to collect ourselves.",
                     "Today we’ll continue to find peace through silence and will turn our minds to the idea that God desires a relationship with each of us.",
                     "Today we’ll continue to find peace through silence and will turn our minds to the idea that God desires a relationship with each of us.",
                     "Today we’ll continue to find peace through silence and will turn our minds to the idea that God desires a relationship with each of us.",
                     "Today we’ll continue to find peace through silence and will turn our minds to the idea that God desires a relationship with each of us.",
                     "Today we’ll continue to find peace through silence and will turn our minds to the idea that God desires a relationship with each of us.",
                     "Today we’ll continue to find peace through silence and will turn our minds to the idea that God desires a relationship with each of us.",
                     "This will be our last introductory session on finding peace in silence with God.  Today we’ll focus on the image of being lifted up by the Holy Spirit.",
                     "This will be our last introductory session on finding peace in silence with God.  Today we’ll focus on the image of being lifted up by the Holy Spirit.",
                     "This will be our last introductory session on finding peace in silence with God.  Today we’ll focus on the image of being lifted up by the Holy Spirit.",
                     "This will be our last introductory session on finding peace in silence with God.  Today we’ll focus on the image of being lifted up by the Holy Spirit.",
                     "This will be our last introductory session on finding peace in silence with God.  Today we’ll focus on the image of being lifted up by the Holy Spirit.",
                     "This will be our last introductory session on finding peace in silence with God.  Today we’ll focus on the image of being lifted up by the Holy Spirit.",
                     "For these next three sessions we’ll learn how to recognize God’s grace and presence throughout our day using a method of reflection known as the Examen.",
                     "For these next three sessions we’ll learn how to recognize God’s grace and presence throughout our day using a method of reflection known as the Examen.",
                     "For these next three sessions we’ll learn how to recognize God’s grace and presence throughout our day using a method of reflection known as the Examen.",
                     "For these next three sessions we’ll learn how to recognize God’s grace and presence throughout our day using a method of reflection known as the Examen.",
                     "For these next three sessions we’ll learn how to recognize God’s grace and presence throughout our day using a method of reflection known as the Examen.",
                     "For these next three sessions we’ll learn how to recognize God’s grace and presence throughout our day using a method of reflection known as the Examen.",
                     "Today we’ll continue to practice reflecting and finding God in our day, but with a focus on recognizing what we’re most grateful for. ",
                     "Today we’ll continue to practice reflecting and finding God in our day, but with a focus on recognizing what we’re most grateful for. ",
                     "Today we’ll continue to practice reflecting and finding God in our day, but with a focus on recognizing what we’re most grateful for. ",
                     "Today we’ll continue to practice reflecting and finding God in our day, but with a focus on recognizing what we’re most grateful for. ",
                     "Today we’ll continue to practice reflecting and finding God in our day, but with a focus on recognizing what we’re most grateful for. ",
                     "Today we’ll continue to practice reflecting and finding God in our day, but with a focus on recognizing what we’re most grateful for. ",
                     "Today we’ll complete our introduction to the Examen and will look more closely at the challenges and obstacles of the day.",
                     "Today we’ll complete our introduction to the Examen and will look more closely at the challenges and obstacles of the day.",
                     "Today we’ll complete our introduction to the Examen and will look more closely at the challenges and obstacles of the day.",
                     "Today we’ll complete our introduction to the Examen and will look more closely at the challenges and obstacles of the day.",
                     "Today we’ll complete our introduction to the Examen and will look more closely at the challenges and obstacles of the day.",
                     "Today we’ll complete our introduction to the Examen and will look more closely at the challenges and obstacles of the day.",
                     "Today will be our first session focused on engaging in conversation with God.  We’ll be using a method of prayer called “Lectio Divina” - our first method that directly incorporates the Bible.",
                     "Today will be our first session focused on engaging in conversation with God.  We’ll be using a method of prayer called “Lectio Divina” - our first method that directly incorporates the Bible.",
                     "Today will be our first session focused on engaging in conversation with God.  We’ll be using a method of prayer called “Lectio Divina” - our first method that directly incorporates the Bible.",
                     "Today will be our first session focused on engaging in conversation with God.  We’ll be using a method of prayer called “Lectio Divina” - our first method that directly incorporates the Bible.",
                     "Today will be our first session focused on engaging in conversation with God.  We’ll be using a method of prayer called “Lectio Divina” - our first method that directly incorporates the Bible.",
                     "Today will be our first session focused on engaging in conversation with God.  We’ll be using a method of prayer called “Lectio Divina” - our first method that directly incorporates the Bible.",
                     "Today we’re going to practice entering into conversation with God again through another passage, but this time will try to imagine ourselves in the story.",
                     "Today we’re going to practice entering into conversation with God again through another passage, but this time will try to imagine ourselves in the story.",
                     "Today we’re going to practice entering into conversation with God again through another passage, but this time will try to imagine ourselves in the story.",
                     "Today we’re going to practice entering into conversation with God again through another passage, but this time will try to imagine ourselves in the story.",
                     "Today we’re going to practice entering into conversation with God again through another passage, but this time will try to imagine ourselves in the story.",
                     "Today we’re going to practice entering into conversation with God again through another passage, but this time will try to imagine ourselves in the story.",
                     "Welcome to your final introductory session!  Today we’re going to listen to another passage and will focus on how to carry it forward into our days.",
                     "Welcome to your final introductory session!  Today we’re going to listen to another passage and will focus on how to carry it forward into our days.",
                     "Welcome to your final introductory session!  Today we’re going to listen to another passage and will focus on how to carry it forward into our days.",
                     "Welcome to your final introductory session!  Today we’re going to listen to another passage and will focus on how to carry it forward into our days.",
                     "Welcome to your final introductory session!  Today we’re going to listen to another passage and will focus on how to carry it forward into our days.",
                     "Welcome to your final introductory session!  Today we’re going to listen to another passage and will focus on how to carry it forward into our days.",
                     "Placeholder",
                     "Placeholder"]
        
        let guide = ["Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Francis",
                     "Francis",
                     "Abby",
                     "Abby",
                     "Abby",
                     "Francis",
                     "Abby"]
        
        let length = ["5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "5 mins",
                      "10 mins",
                      "15 mins",
                      "20 sec",
                      "20 sec"]
        
        let audio = ["audio/Meditation - 5 mins - F - 1.mp3",
                     "audio/Meditation - 10 mins - F - 1.mp3",
                     "audio/Meditation - 15 mins - F - 1.mp3",
                     "audio/Meditation - 5 mins - A - 1.mp3",
                     "audio/Meditation - 10 mins - A - 1.mp3",
                     "audio/Meditation - 15 mins - A - 1.mp3",
                     "audio/Meditation - 5 mins - F - 2.mp3",
                     "audio/Meditation - 10 mins - F - 2.mp3",
                     "audio/Meditation - 15 mins - F - 2.mp3",
                     "audio/Meditation - 5 mins - A - 2.mp3",
                     "audio/Meditation - 10 mins - A - 2.mp3",
                     "audio/Meditation - 15 mins - A - 2.mp3",
                     "audio/Meditation - 5 mins - F - 3.mp3",
                     "audio/Meditation - 10 mins - F - 3.mp3",
                     "audio/Meditation - 15 mins - F - 3.mp3",
                     "audio/Meditation - 5 mins - A - 3.mp3",
                     "audio/Meditation - 10 mins - A - 3.mp3",
                     "audio/Meditation - 15 mins - A - 3.mp3",
                     "audio/Examen - 5 mins - F - 1.mp3",
                     "audio/Examen - 10 mins - F - 1.mp3",
                     "audio/Examen - 15 mins - F - 1.mp3",
                     "audio/Examen - 5 mins - A - 1.mp3",
                     "audio/Examen - 10 mins - A - 1.mp3",
                     "audio/Examen - 15 mins - A - 1.mp3",
                     "audio/Examen - 5 mins - F - 2.mp3",
                     "audio/Examen - 10 mins - F - 2.mp3",
                     "audio/Examen - 15 mins - F - 2.mp3",
                     "audio/Examen - 5 mins - A - 2.mp3",
                     "audio/Examen - 10 mins - A - 2.mp3",
                     "audio/Examen - 15 mins - A - 2.mp3",
                     "audio/Examen - 5 mins - F - 3.mp3",
                     "audio/Examen - 10 mins - F - 3.mp3",
                     "audio/Examen - 15 mins - F - 3.mp3",
                     "audio/Examen - 5 mins - A - 3.mp3",
                     "audio/Examen - 10 mins - A - 3.mp3",
                     "audio/Examen - 15 mins - A - 3.mp3",
                     "audio/Lectio - 5 mins - F - 1.mp3",
                     "audio/Lectio - 10 mins - F - 1.mp3",
                     "audio/Lectio - 15 mins - F - 1.mp3",
                     "audio/Lectio - 5 mins - A - 1.mp3",
                     "audio/Lectio - 10 mins - A - 1.mp3",
                     "audio/Lectio - 15 mins - A - 1.mp3",
                     "audio/Lectio - 5 mins - F - 2.mp3",
                     "audio/Lectio - 10 mins - F - 2.mp3",
                     "audio/Lectio - 15 mins - F - 2.mp3",
                     "audio/Lectio - 5 mins - A - 2.mp3",
                     "audio/Lectio - 10 mins - A - 2.mp3",
                     "audio/Lectio - 15 mins - A - 2.mp3",
                     "audio/Lectio - 5 mins - F - 3.mp3",
                     "audio/Lectio - 10 mins - F - 3.mp3",
                     "audio/Lectio - 15 mins - F - 3.mp3",
                     "audio/Lectio - 5 mins - A - 3.mp3",
                     "audio/Lectio - 10 mins - A - 3.mp3",
                     "audio/Lectio - 15 mins - A - 3.mp3",
                     "audio/Samples - F.mp3",
                     "audio/Samples - A.mp3"]
        var i = 0
        
        for file in files {
            let db = Firestore.firestore()
            db.collection(category).document(file).setData([
                "Name": file,
                "Title": title[i],
                "Index": i,
                "Description": desc[i],
                "Description 2": desc2[i],
                "Guide": guide[i],
                "Length": length[i],
                "Audio": audio[i]
            ]) { err in
                if let err = err {
                    fatalError("Error adding document: \(err)")
                } else {
                    print("Document added")
                }
            }
            i += 1
        }
    }
    
}
